version: '3.11'

services:
  web:
    build:
      context: .
    container_name: django_app
    command: python3 manage.py runserver --noreload 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    depends_on: []
